### ISSUE TITLE
Enhancement: Generate multiple resume from single repository

### ISSUE THREAD

**Issue by Harish2997** [maxboeck/resume#1]
Trying to generate multiple resumes through a single repository where a user who wishes to generate their resume can view it by adding their name as a path.
For example - https://demo-resume.netlify.app/abc returns the resume of the person whose name is abc.
What type of changes to be done in order to obtain the expected result?

**Comment by maxboeck** [comment]
this would require a rewrite to change the structure of the input files used.

currently, the page that actually generates the `index.html` output is the `introduction.md`. there is data from multiple other sources, like the `data` and `entries` directories.

off the top of my head, all of that data would have to be included in a user-specific folder that generates individual pages based on a slug.

at the moment, that is beyond the scope of this project though.

**Comment by Harish2997** [comment]
Sorry I didn't get the notification of your comment. 
So, basically I'm trying to develop this as my school project where my classmates can upload their resume in a single repo, which would be very much helpful for our placements.

I was able to split the project into individual pages by adding the `introduction.md` in a separate folder with the `entries` in it. The problem is all the `entries` data in the project gets displayed instead of specific individuals `entries`.
It would be very much helpful if you can guide me through the process.

**Comment by maxboeck** [comment]
@Harish2997 sorry this is out of scope for the project - you're free to fork the repo and make your own multi-user version.
