### ISSUE TITLE
What Node version is needed?

### ISSUE THREAD

**Issue by Lazza** [maxboeck/resume#3]
I am trying to `npm install` with Node 14 on macOS 10.15 and it seems to crash during the `node-gyp` installation phase.

My guess is that I am using the wrong Node version and maybe I should try with another one, but I do not see it mentioned in the README.

Could you clarify if a specific Node version is needed?

Thank you!

**Comment by Lazza** [comment]
OK, I got it working with:

    npm install node@10

It could be nice to mention this in the README. 🙂

**Comment by maxboeck** [comment]
@Lazza ah yes, I just recently added a node version hint for NVM: see https://github.com/maxboeck/resume/commit/82c7cbaf2d673e80372f8a9acaff3ed05f016448

originally made with 10.15, I thought it would work with newer versions anyway, but apparently the spell-checking feature makes some problems in node 14.

will add to README, thx

**Comment by Lazza** [comment]
Thank you for the great work!

**Comment by maxboeck** [comment]
thanks for using it 😉
