### ISSUE TITLE
Feature suggestion: translated strings

### ISSUE THREAD

**Issue by Lazza** [maxboeck/resume#4]
I know this might be a bit out of scope, but it could be a nice feature. 🙂 

Yesterday I finished working on my CV and I added this to the metadata:

    "lang": "it",
    "locale": "it_it",

Nevertheless, there were a few English strings here and there that needed to be changed manually. I fixed the linter too by adding the language to the spell checker:

    SpellChecker.setDictionary('it');
    const results = SpellChecker.checkSpelling(text)

I was wondering if it could be possible to extract all the strings and put them in a single dictionary file, so users can translate that single file in their own language.

**Comment by maxboeck** [comment]
@Lazza excellent feature suggestion! I extracted all hardcoded strings into a separate data file in `data/strings.json` - should be easier to translate these now. updated the README as well.

thanks!
