### ISSUE TITLE
Feature suggestion: legal boilerplate section

### ISSUE THREAD

**Issue by Lazza** [maxboeck/resume#5]
Due to privacy laws, some countries **require** people to add a legal note at the bottom, otherwise recruiters or other subjects are forbidden from considering the personal data in the CV.

It could be nice to add it as an option. For example, I hardcoded one [here](https://cv.andrealazzarotto.com/):

```
<section class="section" id="legal">
<p><small>Autorizzo il trattamento dei dati personali contenuti nel mio curriculum vitae in base all’art. 13 del D. Lgs. 196/2003 e all’art. 13 del Regolamento UE 2016/679 relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali.</small></p>
</section>
```

**Comment by maxboeck** [comment]
@Lazza ah good point (and nice CV btw!)
I'd like to keep this flexible, but I can imagine adding a "freeform" section.

i.e. there would be a `custom.md` file that would just print any content in an optional section at the bottom.

**Comment by Lazza** [comment]
Thank you very much!

**Comment by maxboeck** [comment]
@Lazza I've restructured the source files a bit. There is now a `src/entries/content/custom.md` file that can be used to achieve a legal disclaimer (or any other custom section).

for this particular usecase, one would remove the title from the file's frontMatter, and wrap the disclaimer text in `<small>`.

thanks for the input, I hope that solves your Issue!

**Comment by Lazza** [comment]
Thank you very much!

I will check it out soon, I hope, but at first glance it seems precisely
what I was looking for.
