### ISSUE TITLE
Question: adding new icons

### ISSUE THREAD

**Issue by janKollars** [maxboeck/resume#8]
Thank you Max for the very cool template!

Did you download the icons from a specific repository? I was adding icons for the social media links and was worried about visual consistency.

**Comment by Lazza** [comment]
They are Material Icons, I guess.

https://material.io/resources/icons/?style=baseline

**Comment by janKollars** [comment]
They are indeed!
Still I am not sure where the social media icons such as GitHub or Linkedin are from. I assume they are fetched directly from the respective website (/ press kit).

**Comment by maxboeck** [comment]
@Lazza @janKollars sorry guys, was really busy at work. You guessed correctly, they are from the material set. the social logos are taken from https://boxicons.com/. lots more there.
